### ISSUE TITLE
TODO: 反盗猎平台 2022.1

### ISSUE THREAD

**Issue by PIG208** [Henry3510/anti-poaching-platform#2]
截至今天(2022.1.12)，目前已经完成的部分:

- [x] 项目容器化
- [x] 数据库迁移
- [x] 物种信息表及对应接口
- [x] 部分单元测试

计划完成的部分:
- [x] 通用REST API接口 (及相应model)
    - [x] 判决书
    - [x] 来源/目的
    - [x] 盗猎者信息
- [ ] 内部pipeline接口
- [ ] Redis缓存
- [ ] 任务队列 (处理耗时的数据清洗, nlp工作)
- [ ] 博客系统API接口
- [ ] async sqlalchemy sessions
- [ ] GraphQL 支持
